### ISSUE TITLE
Style Slider and Main container 

### ISSUE THREAD

**Issue by devmanusanram** [likeconan/react-avatar-image-cropper#10]
Need help to style the slider and main container on of the cropper. Tried to add style objects via the `rootStyle` and `sliderConStyle`.
Also, I have the issue that some images that I have cropped are cut in half the height I pass when cropping.

**Comment by likeconan** [comment]
@ManuSanRam  Hi, I updated the documents and add more props of style to configure. Please check it out and have a try.

Also, could you provide the code so that I can resolve the height cut in half issue. Thanks
