### ISSUE TITLE
Uncaught ReferenceError: sliderDiv is not defined

### ISSUE THREAD

**Issue by thevictorchen** [likeconan/react-avatar-image-cropper#11]
I get this error after uploading an image. I used your example on the site.

Uncaught ReferenceError: sliderDiv is not defined
    at AvatarImageCropper.render (react-avatar-image-cropper.js:728)

**Comment by likeconan** [comment]
Thanks for telling me that. This is resolved in 1.3.2 version @thevictorchen

**Comment by thevictorchen** [comment]
great! works for me now. thanks @likeconan.
