### ISSUE TITLE
Apply method doesn't work

### ISSUE THREAD

**Issue by roberts98** [likeconan/react-avatar-image-cropper#15]
Hi, I want to use your module, but I don't have access to the cropped photo.
I'm following instructions but apply method seems to be not working, because when I have console.log or whatever in the function, it's not logging anything.

My code:
```import React from "react";
import AvatarImageCropper from "react-avatar-image-cropper";

function ImageCropper() {
  function apply(file) {
    var src = window.URL.createObjectURL(file);
    console.log("test");
  }

  return (
    <div
      style={{
        width: "250px",
        height: "250px",
        margin: "auto",
        border: "1px solid black"
      }}
    >
      <AvatarImageCropper apply={apply} />
    </div>
  );
}

export default ImageCropper;
```

**Comment by likeconan** [comment]
@roberts98  Hi, I tried with your code, but it did work. Could you please provide more information about this issue? Like the full code or what version of react did you use?

**Comment by roberts98** [comment]
Ok, I made new react app with CRA and it works and I know why it didn't work on my projekt.
I had wrapper div with overflow hidden and I actually  didn't see the bar with buttons and zooming.
