### ISSUE TITLE
How can i get original image too?

### ISSUE THREAD

**Issue by iSarahSajjad** [likeconan/react-avatar-image-cropper#17]
Well im clearly getting the crop image but i want orignal image too how can i get that

**Comment by iSarahSajjad** [comment]
Do you have onChange method that would be very helpful for me..

**Comment by likeconan** [comment]
@iSarahSajjad  You can use React.findDOMNode to get the input target value inside the apply function

**Comment by iSarahSajjad** [comment]
@likeconan and i want to change cancel functionality too. but props of the component didn't let me do it.

**Comment by likeconan** [comment]
![image](https://user-images.githubusercontent.com/12960160/65412106-20609b80-de21-11e9-9118-1497fbce0bfe.png)

I think you can try in my online-demo. And it worked as the image above
