### ISSUE TITLE
How to add default image for crop?

### ISSUE THREAD

**Issue by iSarahSajjad** [likeconan/react-avatar-image-cropper#18]
I need to add default image which is coming from a url.

**Comment by likeconan** [comment]
Hi,

I don't think you can do that. You can view this [add file to input programmly](https://stackoverflow.com/questions/6021526/programmatically-set-the-value-of-a-type-file-input-html-element)

**Comment by iSarahSajjad** [comment]
Then how can I want to crop default image? Without via input.. I really want that..

**Comment by likeconan** [comment]
So far, this library does not support that. Sorry about that

**Comment by iSarahSajjad** [comment]
Ok is there anyway to show crop area without adding into the input field?

**Comment by likeconan** [comment]
You can use a div to wrap the AvatarImageCropper, and that div can show as a crop area

**Comment by iSarahSajjad** [comment]
How to display crop tools apply and cancel on it..
