### ISSUE TITLE
Giving apply/cancel functions to another components

### ISSUE THREAD

**Issue by zaferkaymaz** [likeconan/react-avatar-image-cropper#19]
Hi,

I just try to give apply/cancel functions to another button component which is not implemented on actions is that possible ?

            <Button
              autoFocus
              color="inherit"
              className={theme.saveButton}
              onClick={onApply} -----> For example there
            >
              kaydet
            </Button>

            <Button
              autoFocus
              color="inherit"
              className={theme.abortButton}
              onClick={handleAbort}
            >
              iptal
            </Button>
          </Toolbar>
        </AppBar>

        {!openedScreenState && (
          /*<DialogContent className={theme.dialogScreen}>
            <div className={theme.imageEditor}>
              <ImageCrop
                src={imageSrc}
                crop={imageCrop}
                locked  
                onComplete={handleOnCropComplete}
                onChange={handleOnCropChange}
                onImageLoaded= {handleImageLoaded}
              />
            </div>
          </DialogContent>*/
          <div style={{ width: "720px", height: "360px", margin: "auto" }}>
            <AvatarImageCropper
              apply={onApply}
              text={"Fotoğraf Eklemek için tıklayın"}
            />
          </div>

**Comment by likeconan** [comment]
There are two ways to use your own button.

1. Just add actions prop on AvatarImageCropper which by using of your own Button.

2. If you want to use other button which not on AvatarImageCropper, you can use this code

```
<AvatarImageCropper
          apply={onApply}
          action=[<div/>,<div/>]
          ref={c=>this.avatar = c}
          text={"Fotoğraf Eklemek için tıklayın"}
        />
``` 
Then just fire the avatar event when you click on save button, the function should like below:
```
()=>{
  this.avatar._apply()
}
```

Last but not least, the onApply function on AvatarImageCropper would have the callback with blob

**Comment by zaferkaymaz** [comment]
And it works thanks!
