### ISSUE TITLE
Add errorStyle props & hide error DOM element

### ISSUE THREAD

**Issue by MichaelBieniek** [likeconan/react-avatar-image-cropper#2]
Great component - have one issue / suggestion as I can't override error style without modifying source code directly.

Add a props.errorStyle?
`<p style={{ color: 'red', ...this.props.errorStyle }}>{this.state.errorMsg}</p>`
or even:
`{this.state.errorMsg && <p style={{ color: 'red', ...this.props.errorStyle }}>{this.state.errorMsg}</p>}`
so that it doesn't take up space in the DOM if no errors are present

**Comment by likeconan** [comment]
Thanks Michael,

I will fix that and maybe add an props to replace the <p> element so that you can display the error message any thing you want.

The next release will  be before  3.23 @MichaelBieniek

**Comment by akhilumapathe** [comment]
Any update on this?

**Comment by likeconan** [comment]
> Any update on this?

Thanks for reminding me that, I just released 1.3.7 version and you can implement the errorStyle now. Thanks a lot~
