### ISSUE TITLE
Produce an image larger than the canvas or cropper

### ISSUE THREAD

**Issue by davidhlee** [likeconan/react-avatar-image-cropper#3]
Hi, I'm looking to output and save an image that is larger than the canvas or the image cropper, so that I can save and display larger versions of the image in different places throughout my site. For instance, I want my cropper to be small like this: https://www.dropbox.com/s/siya2px3jmo8yif/Screenshot%202018-03-15%2010.25.50.png?dl=0

But I want it to be able to output images that are larger, like this: https://www.dropbox.com/s/fw0ixqnblpgf34i/Screenshot%202018-03-15%2010.26.31.png?dl=0. I can't seem to figure out how to do that. Once the height and width of the cropper are set, that is the height and width of the image, which isn't very flexible.

Could you show me which variables to adjust in the source code? (sizeH, sizeW, relX, relY, img2D.width, img2D.height)Thanks!

**Comment by likeconan** [comment]
Hi, sorry to respond lately. the img2D.width and img2D.height may can help you, if not. Please open this again and I will try to resolve it.
