### ISSUE TITLE
Text Prop

### ISSUE THREAD

**Issue by vuxor** [likeconan/react-avatar-image-cropper#4]
Is there possibility to change text prop type to node from string?
 I would like text to be:
`<span>Upload photo<br />Drag image or click here</span>`
this is not possible to do now when text prop type is string.

**Comment by likeconan** [comment]
About the text Prop, I will resolve it in next version.

**Comment by likeconan** [comment]
Hi, this is resolved in 1.2.0

Please check it out

**Comment by vuxor** [comment]
Thanks
