### ISSUE TITLE
Cannot read property 'content' of undefined

### ISSUE THREAD

**Issue by ivascu-angelo** [likeconan/react-avatar-image-cropper#52]
Hello Connan, i have a new project where i try to implement the library but im facing the error mentioned in the title.
i did:
1. npm i react-avatar-image-cropper --save
2. import AvatarImageCropper from 'react-avatar-image-cropper';
3. Way im writing code is: 
4.  export default function Avatar() {
  const profileCtx = useContext(ProfileContext);

  const apply = (file) => {
    profileCtx.changeAvatar(window.URL.createObjectURL(file));
  };

  return (
    <div>
      <div className="flex justify-center">
 
        {profileCtx.avatar === "" && (
          <FontAwesomeIcon
            icon={faUserCircle}
            size={"8x"}
            className={"ml-6 mt-2"}
          />
        )}
        {profileCtx.avatar !== "" && (
          <img
            src={profileCtx.avatar}
            alt={profileCtx.avatar}
            width={150}
            height={150}
          />
        )}
      </div>
      <div className={"bg-purple-500"}>
        <AvatarImageCropper
          apply={apply}
          isBack={true}
          text="Upload"
          previewBorderRadius="500px"
        />
      </div>
    </div>
  );
}

Im using Next JS, Tailwind and FontAwesome  but i don't think it matters. any advices about how to proceed ?

I tried to make a brand new project without Next JS but with Typescript and there im not having the same issue.

**Comment by likeconan** [comment]
May I ask, are you using server side rendering in react?

**Comment by likeconan** [comment]
No responding and close it

**Comment by solace** [comment]
For future reference, I just stumbled on this issue. In NextJS I get this error if I don't use `next/dynamic` to load the component.
