### ISSUE TITLE
Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by solace** [likeconan/react-avatar-image-cropper#54]
Hello!

I'm getting the error "Each child in a list should have a unique "key" prop." when I pass in custom `actions` with the key prop set as in your example. Because the key prop is special I don't think `React.cloneElement` is passing them into the clone and it might need to be explicitly set.

**Comment by likeconan** [comment]
I think you can put the key value as others like "cancel","apply" since 0 and 1 are too common

**Comment by solace** [comment]
My apologies, I was unclear.

I used custom values for `key` for my buttons, not 0 and 1, but the warning still appears.

**Comment by likeconan** [comment]
Could you provide one sample? It's kind of hard to identify why it happened

**Comment by solace** [comment]
Oh, sorry, I mistook from where the error was being generated. It's from the `icon` override prop, not `actions`.

If you remove `key="test-key"` from the `icon` in the sandbox below, you'll see the warning in the console.

https://codesandbox.io/s/elastic-brown-khbnk7?file=/src/App.js

**Comment by likeconan** [comment]
Well, don't know why it happened, but yeah, please add key for the `icon` and I will update the documentation. Thanks
