### ISSUE TITLE
Have a crop radius for cropping the image in a circle

### ISSUE THREAD

**Issue by djdips** [likeconan/react-avatar-image-cropper#6]
@likeconan is there a way we can have a border-radius more like crop-radius which we can define in case we need to crop the image in a circle, kindly advise

**Comment by likeconan** [comment]
Thanks for your advise. However, the image cropped must be in rectangle which means if we add border-radius, the  radius part  should be transparent and  the output must always be .png. Maybe someday I will resolve it if it really helps you and it is what you want
