### ISSUE TITLE
How I can upload the image to php server after I croped using this library

### ISSUE THREAD

**Issue by M4Lien** [likeconan/react-avatar-image-cropper#7]
Hi, How are you?
I am using your library (react-avatar-image-cropper) in order to crop the image.
But I have to upload this image to my php server.
This code is the following as:

handleSubmit(e){
      const formData = new FormData();
      formData.append("file", this.state.image, this.state.image.name);
      axios.post('myserver.com/api/avatar', formData);
}

apply(file){
     this.setState({image:file});
}

render().....
<
AvatarImageCropper apply={this.apply} />

It didn't work, but it works well without your library as following:
<
input type="file" onChange="this.onChangeImage" />

onChangeImage(e){
     this.setState({image: e.target.files[0]});
}

How I can solve this issue?

**Comment by likeconan** [comment]
Hello @M4Lien ,
the apply function return Blob not File, so the only thing you need to do is just convert blob to file According to your code, you can try it like below:

``` js
apply(blob){
  var file = new File([blob],'filename.jpg')
   this.setState({image:file});
}
```

**Comment by M4Lien** [comment]
Hello @likeconan ,
I've tried to solve this issue with code. It works well.
Thank you for your hospitality.
By the way, I have a doubt.
If i press "upload photo" button, it will open file browser, so I can choose the proper avatar.
but when it will be opend, it takes the time a long.
How can I solve this issue?

**Comment by M4Lien** [comment]
sorry, this issue was my computer memory capability.
Now it works well.
