### ISSUE TITLE
Crop 2 images(background-image and image) into a single output image. (Feature Requested)

### ISSUE THREAD

**Issue by svenkatesh-nyros** [likeconan/react-avatar-image-cropper#8]
Is it possible to provide the source image in a existing background image to crop them into single image using this package.
following is the example working urls for making this feature.

http://subinsb.com/create-profile-picture-framer-web-app/

Git url: https://github.com/subins2000/profile-picture-framer

can this feature implemented in your package ?

**Comment by likeconan** [comment]
I think you can use my package first to crop a 400*400 profile image, then you can get the blob from apply function. So that you can handle it with other library as you want.
